<?php

/**
 * PluginSmtAPIWrapperSetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSmtAPIWrapperSetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSmtAPIWrapperSetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSmtAPIWrapperSet');
    }
}