<?php

/**
 * PluginSmtApiWrapperSetParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSmtApiWrapperSetParameterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSmtApiWrapperSetParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSmtApiWrapperSetParameter');
    }
    
}